import Head from "next/head";
import Link from "next/link";
import { useTranslation } from "next-i18next";
import styles from "../styles/Home.module.css";

export default function Home() {
  const { t } = useTranslation("common");
  return (
    <div className={styles.container}>
      <Head>
        <title>{t("Vaults of Vaarn Generator")}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{t("Generators for Vaults of Vaarn")}</h1>

        <p className={styles.description}>
          {t(
            "Vaults of Vaarn is a rad RPG made by Leo Hunt about exploring a world of blue sand and abandoned ruins. Pick out a thing you want to generate below and enjoy!"
          )}
        </p>
        <Link href="/characters">{t("Characters")}</Link>
      </main>
    </div>
  );
}
